UMC-CommonPlant/CommonPlant-Server-Refactoring

src/main/java/com/umc/commonplant/global/exception/BadRequestException.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponse.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java, src/main/java/com/umc/commonplant/global/exception/ExceptionAdvice.java, src/main/java/com/umc/commonplant/global/exception/ForbiddenException.java, src/main/java/com/umc/commonplant/global/exception/GlobalException.java, src/main/java/com/umc/commonplant/global/exception/MethodNotAllowedException.java, src/main/java/com/umc/commonplant/global/exception/NotFoundException.java
- close #2 
- 예외처리를 위한 exception handler 로직 작성
- 
- 선택 사항
=> [Feat] 예외처리를 위한 ExceptionHandler 로직 추가

src/main/java/com/umc/commonplant/CommonplantApplication.java, src/main/java/com/umc/commonplant/domain/BaseTime.java, src/main/java/com/umc/commonplant/domain/alarm/entity/Alarm.java, src/main/java/com/umc/commonplant/domain/belong/entity/Belong.java, src/main/java/com/umc/commonplant/domain/comment/entity/Comment.java, src/main/java/com/umc/commonplant/domain/friend/entity/Friend.java, src/main/java/com/umc/commonplant/domain/history/entity/History.java, src/main/java/com/umc/commonplant/domain/image/entity/Image.java, src/main/java/com/umc/commonplant/domain/info/entity/Info.java, src/main/java/com/umc/commonplant/domain/keyword/entity/Keyword.java, src/main/java/com/umc/commonplant/domain/like/entity/Like.java, src/main/java/com/umc/commonplant/domain/memo/entity/Memo.java, src/main/java/com/umc/commonplant/domain/place/entity/Place.java, src/main/java/com/umc/commonplant/domain/plant/entity/Plant.java, src/main/java/com/umc/commonplant/domain/qna/entity/QnA.java, src/main/java/com/umc/commonplant/domain/story/entity/Story.java, src/main/java/com/umc/commonplant/domain/user/entity/User.java
- 도메인 초기 세팅
- 작성한 ERD를 토대로 entity 설정 완료
- 초기 ERD를 참고하여 작성한 Entity로 앞으로 개발을 진행하시면서 수정하시면 될것 같습니다!
- 선택 사항
=> [Feat] 도메인 초기 세팅 완료

src/main/java/com/umc/commonplant/global/config/FCMConfig.java
- #15 
- Firebase 설정 수정
- Client Key의 이름이 코드에 작성되어있어 수정
- 선택 사항
=> [Fix] FCM Config 수정

build.gradle, src/main/java/com/umc/commonplant/domain/alarm/controller/AlarmController.java, src/main/java/com/umc/commonplant/domain/alarm/dto/FCMMessageDto.java, src/main/java/com/umc/commonplant/domain/alarm/dto/FCMMessageTestDto.java, src/main/java/com/umc/commonplant/domain/alarm/entity/Alarm.java, src/main/java/com/umc/commonplant/domain/alarm/service/AlarmService.java, src/main/java/com/umc/commonplant/domain/alarm/service/FCMService.java
- close #17 
- Firebase Cloud Messaging API 초기 설정
- Firebase Cloud Messaging API 초기 설정
=> [Feat] Firebase Cloud Messaging API 초기 설정

src/main/java/com/umc/commonplant/global/dto/JsonResponse.java
- 모든 도메인에서 사용할 JsonResponse 템플릿 추가
- JsonResponse 템플릿 추가
- 
- 선택 사항
=> [Feat] JsonResponse 추가

build.gradle, src/main/java/com/umc/commonplant/domain/belong/entity/Belong.java, src/main/java/com/umc/commonplant/domain/belong/entity/BelongRepository.java, src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/domain/place/dto/PlaceDto.java, src/main/java/com/umc/commonplant/domain/place/entity/Place.java, src/main/java/com/umc/commonplant/domain/place/entity/PlaceRepository.java, src/main/java/com/umc/commonplant/domain/place/service/PlaceService.java
- #18 
- place 도메인 설정 및 createPlace 기능 추가
- 추가해야할 기능 많음
- 유저 및 이미지 필요
- 선택 사항
=> [Feat] createPlace 기능 추가

build.gradle, src/main/java/com/umc/commonplant/domain/Jwt/JwtSecret.java, src/main/java/com/umc/commonplant/domain/Jwt/JwtService.java, src/main/java/com/umc/commonplant/domain/story/entity/Story.java, src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/domain/user/dto/KakaoProfile.java, src/main/java/com/umc/commonplant/domain/user/dto/UserDto.java, src/main/java/com/umc/commonplant/domain/user/entity/User.java, src/main/java/com/umc/commonplant/domain/user/repository/UserRepository.java, src/main/java/com/umc/commonplant/domain/user/service/OAuthService.java, src/main/java/com/umc/commonplant/domain/user/service/UserService.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java, src/main/java/com/umc/commonplant/global/utils/UuidUtil.java
-
- User 도메인 join메서드와 join에서 생성된 uuid로 회원조회 구현
- [ V] Merge 하려는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ V] 작업한 API에 대해 적절한 **예외처리**가 이루어졌는가?
- [ V] Merge 하려는 PR 및 Commit들을 **로컬**에서 실행했을 때 에러가 발생하지 않았는가?
- 
- 선택 사항
=> [Feat] User Domain

src/main/java/com/umc/commonplant/domain/image/controller/ImageController.java, src/main/java/com/umc/commonplant/domain/image/service/ImageService.java
- close #14 
- Image 서비스 내의 encoding warning 해결
- 
- 선택 사항
=> [Fix] encoding warning in Image code

src/main/java/com/umc/commonplant/domain2/info/controller/InfoController.java, src/main/java/com/umc/commonplant/domain2/info/dto/InfoDto.java, src/main/java/com/umc/commonplant/domain2/info/service/InfoService.java
-  #25 
- Information 부분의 단순 추가(예외처리 제외) 
- 이름으로 조회
-
=> [Feat] modify createInfo and findInfo

build.gradle, src/main/java/com/umc/commonplant/domain/belong/entity/BelongRepository.java, src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/domain/place/dto/PlaceDto.java, src/main/java/com/umc/commonplant/domain/place/service/PlaceService.java, src/main/java/com/umc/commonplant/domain/weather/entity/Weather.java, src/main/java/com/umc/commonplant/domain/weather/entity/WeatherRepository.java, src/main/java/com/umc/commonplant/domain/weather/service/WeatherService.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java, src/main/java/com/umc/commonplant/global/utils/openAPI/OpenApiService.java, src/main/java/com/umc/commonplant/global/utils/openAPI/PlaceInfo.java, src/main/java/com/umc/commonplant/global/utils/openAPI/WeatherDeserializer.java, src/main/java/com/umc/commonplant/global/utils/openAPI/WeatherResult.java
- #36 
- getPlace : 장소 정보, 유저 리스트 조회 (식물 리스트 조회 적용 전)
- getPlaceWeather : 장소 위치로 날씨 API 조회 및 데이터베이스에 저장 후 사용
- 날씨 조회가 오래 걸릴 때 중복 데이터가 쌓이는 경우가 발생 -> DB 조회시 limit 1 조건을 걸어 조회할 수 있도록 변경
- getPlace API에 식물 리스트 조회 적용
- kakaoMap open API : https://developers.kakao.com/docs/latest/ko/local/dev-guide
- 기상청 단기 예보 조회 : https://www.data.go.kr/data/15043494/fileData.do
- json deserialize : https://velog.io/@yevini118/SpringBoot-Json-Deserialize-%ED%95%98%EA%B8%B0
=> [Feat] getPlace, getPlaceWeather 구현

src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java
- #39 
- 도메인 별로 Error Table 번호 나누기
-
=> [Chore] 도메인별로 Error Table 나누기 완료

src/main/java/com/umc/commonplant/domain/plant/controller/PlantController.java, src/main/java/com/umc/commonplant/domain/plant/dto/PlantDto.java, src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java
- #26 
- 식물 추가: 예외 처리 추가
- 식물 수정할 때 닉네임과 이미지만 불러오는 API(화면) 추가
- https://github.com/UMC-CommonPlant/CommonPlant-Server-Refactoring/pull/44
- 식물 조회 API 수정
- 선택 사항
=> [FIX]: 식물 도메인 POST, GET 관련 예외 처리 추가

src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/domain/place/dto/PlaceDto.java, src/main/java/com/umc/commonplant/domain/plant/controller/PlantController.java, src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java
- #26 
- https://github.com/UMC-CommonPlant/CommonPlant-Server-Refactoring/pull/51
- My Place 메인 화면 연동 성공
- 최근 메모 내용 불러오기!
- 선택 사항
=> [FIX]: 식물 도메인 POST, GET 연동

src/main/java/com/umc/commonplant/domain/place/service/PlaceService.java, src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java
- 장소 참여인원 추가 수정
- 장소 참여인원 추가 수정
- 예외처리
- 
- 선택 사항
=> [Chore] : Fix Place newFriends API, exception

.github/workflows/gradle.yml, appspec.yml, scripts/deploy.sh
- #61 
- GitActions CI/CD 설정 및 테스트
=> GitActions main 브랜치 CI/CD 설정 및 테스트

src/main/java/com/umc/commonplant/domain/belong/entity/BelongRepository.java, src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/domain/place/dto/PlaceDto.java, src/main/java/com/umc/commonplant/domain/place/entity/PlaceRepository.java, src/main/java/com/umc/commonplant/domain/place/service/PlaceService.java, src/main/java/com/umc/commonplant/domain/plant/dto/PlantDto.java, src/main/java/com/umc/commonplant/domain/plant/entity/PlantRepository.java, src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java
- 메인화면 
- 메인화면 name, placeList, plantList 불러오기
- placeList 최근 등록순으로 정렬
- plantList 물주기날짜순으로 정렬
- 
- 선택 사항
=> [FEAT] : add main view (myGarden)

build.gradle, src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/domain/user/dto/UserDto.java, src/main/java/com/umc/commonplant/domain/user/repository/UserRepository.java, src/main/java/com/umc/commonplant/domain/user/service/UserService.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java
- 이름 중복체크
- 이름 중복체크 boolean값으로 반환
- 사용중인 이름인 경우 예외처리
- 2자이하 10자이상인 경우 예외처리
- 
- 선택 사항
=> [Feat] #67 이름 중복체크

src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/domain/user/service/UserService.java
- 이름으로 유저 조회
-  기존 uuid조회에서 이름 조회로 변경 
- 
- 선택 사항
=> [Refactor] #68 이름으로 유저조회

build.gradle, src/main/java/com/umc/commonplant/domain/image/controller/ImageController.java, src/main/java/com/umc/commonplant/domain/place/controller/PlaceSwagger.java, src/main/java/com/umc/commonplant/global/config/SwaggerConfig.java
- #64 
- springfox 라이브러리가 2020년 이후로 업데이트 중단
- springdoc으로 변경하여 적용
=> Chore : springfox -> springdoc 변경

src/main/java/com/umc/commonplant/domain2/info/controller/InfoController.java, src/main/java/com/umc/commonplant/domain2/info/controller/InfoSwagger.java, src/main/java/com/umc/commonplant/domain2/info/dto/InfoDto.java, src/main/java/com/umc/commonplant/global/utils/MultipartJackson2HttpMessageConverter.java
- #25 
- InfoController와 InfoSwagger에 Swagger 어노테이션 추가
- Infodto Swagger 어노테이션 추가
- utils/MultipartJackson2HttpMessageConverter 추가
- 
- 선택 사항
=> [Feat] Information Swagger 적용

src/main/java/com/umc/commonplant/domain/belong/entity/BelongRepository.java, src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/domain/place/dto/PlaceDto.java, src/main/java/com/umc/commonplant/domain/place/entity/Place.java, src/main/java/com/umc/commonplant/domain/place/service/PlaceService.java
- #18 
- 사용자가 속한 장소 리스트 완료
- 장소에 속한 친구 리스트 조회 완료
=> [Feat] 사용자가 속한 장소 리스트, 장소에 속한 친구 리스트 조회

src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/domain/user/service/UserService.java
- 사용자정보를 불러올때 등록된 유저가 없다는 에러 발생
-  getUser() 와 getUserByName() 분리
- 회원가입시 이미지가 안들어가는 문제 수정 
- 모든 메서드에서 사용자 정보를 불러올 때 4003 에러 안뜨게 수정
- 회원가입 시 이미지 저장 
- 선택 사항
=> [Fix] : 사용자 정보 불러올 때 4003 에러 수정

src/main/java/com/umc/commonplant/domain/plant/controller/PlantController.java, src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java
- #26 
- 식물 수정, 식물 삭제 API 추가
- 식물 물주기 날짜 관련 로직 수정 **(사용자가 설정한 주기에 맞게 계산)** @hweyoung @uhyunglee 
- 모든 식물 도메인 API에 장소 권한 예외처리 추가 **(GET 제외)**
- 주석 정리
- swagger 적용
- 예외처리 점검
- 중복된 예외처리를 `belongUserOnPlace` 함수처럼 하나의 함수로 분리해서 사용
- [클린 코드(Clean Code) 요약 및 정리](https://dev-coco.tistory.com/182)
=> [Feat] 식물 수정, 식물 삭제 관련 API

src/main/java/com/umc/commonplant/domain/belong/entity/BelongRepository.java, src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/domain/place/controller/PlaceSwagger.java, src/main/java/com/umc/commonplant/domain/place/dto/PlaceDto.java, src/main/java/com/umc/commonplant/domain/place/service/PlaceService.java
- #18 
- Place의 모든 API에 Swagger 적용 완료
=> [Feat] Place Swagger 적용 완료

.github/workflows/gradle.yml
- #61 
- 배포 브랜치 변경 main -> master
=> [Chore] 배포 브랜치 main -> master

src/main/java/com/umc/commonplant/domain/oauth/controller/OAuthController.java, src/main/java/com/umc/commonplant/domain/oauth/controller/OAuthSwagger.java, src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/domain/user/controller/UserSwagger.java, src/main/java/com/umc/commonplant/domain/user/dto/UserDto.java
-
-  회원가입
- 이름으로 회원조회
- 이름 중복검사
- 카카오로그인
- Swagger UI 적용
- 선택 사항
=> [Feat] User Domain, Kakao Login Swagger 적용

src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java
- https health check를 위한 API 설정
=> [Feat] HealthCheck Method 추가

src/main/java/com/umc/commonplant/global/config/SwaggerConfig.java
- [Fix] Swagger Failed to Fetch
-  swagger open api 요청 url  서버 url과 같게 수정 
- 
- 선택 사항
=> [Fix] Swagger Failed to Fetch

src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/global/config/SwaggerConfig.java
- request url과 sever url이 일치 하지 않아 발생하는 에러, Swagger Failed to Fetch 
- swagger open api 요청 url 서버 url과 같게 로직 수정
- 
- 선택 사항
=> [Fix] Swagger Faild to Fetch

src/main/java/com/umc/commonplant/domain/Jwt/JwtSecret.java
- JWT토큰 유효기간 변경
- JWT 토큰 기간 30일로 변경(테스트용)
- 
- 선택 사항
=> [Refactor] Extension JWT Token

src/main/java/com/umc/commonplant/domain/Jwt/JwtSecret.java
-  JWT 토큰 유효기간 변경 
- 기존 7일
- 변경 24일
- 
- 선택 사항
=> [Chore] Extension JWT Token

src/main/java/com/umc/commonplant/domain/user/dto/UserDto.java, src/main/java/com/umc/commonplant/domain/user/entity/User.java, src/main/java/com/umc/commonplant/domain/user/repository/UserRepository.java, src/main/java/com/umc/commonplant/domain/user/service/UserService.java
- 회원가입시 providerId 도 DB에 저장되게 수정
- providerId 추가
- 
- 선택 사항
=> [Refactor] Refactor join User Logic

src/main/java/com/umc/commonplant/domain/alarm/controller/AlarmController.java, src/main/java/com/umc/commonplant/domain/alarm/dto/FCMMessageDto.java, src/main/java/com/umc/commonplant/domain/alarm/dto/FCMMessageTestDto.java, src/main/java/com/umc/commonplant/domain/alarm/service/FCMService.java
- #103 
- #19 
- 기존 코드에 발급 받은 FCM Token를 연동해서 테스트 할 수 있게 코드 수정
- 기존 코드에 발급 받은 FCM Token를 연동해서 테스트 할 수 있게 코드 수정
- 추후 `FCMMessageTestDto`에서 `FCMMessageDto`로 수정
- 기획 참고해서 모든 로직에 알람이 적용되도록 수정
=> [Fix] Alarm Domain: FCM Token 연결

src/main/java/com/umc/commonplant/domain/oauth/controller/OAuthController.java, src/main/java/com/umc/commonplant/domain/oauth/controller/OAuthSwagger.java
- 토큰 유효성 검사 API 
- 토큰 유효성 검사 가능 
- 
- 선택 사항
=> [Feat] token valid API

src/main/java/com/umc/commonplant/domain/Jwt/JwtService.java, src/main/java/com/umc/commonplant/domain/oauth/controller/OAuthController.java, src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/domain/user/controller/UserSwagger.java, src/main/java/com/umc/commonplant/domain/user/dto/UserDto.java
- 토큰 유효성 검사 API
- 토큰 유효성 검사 API
- 
- 선택 사항
=> [Refactor] token valid API

src/main/java/com/umc/commonplant/domain2/info/controller/InfoController.java, src/main/java/com/umc/commonplant/domain2/info/controller/InfoSwagger.java, src/main/java/com/umc/commonplant/domain2/info/dto/InfoDto.java, src/main/java/com/umc/commonplant/domain2/info/service/InfoService.java
=> [Feat] create new API SearchInfo with waterday

src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/domain/place/dto/PlaceDto.java, src/main/java/com/umc/commonplant/domain/place/service/PlaceService.java
- #18 
- getPlaceBelongUser API response dto 우선 수정 후 배포
=> [Chore] getPlaceBelongUser 수정

src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/domain/user/controller/UserSwagger.java, src/main/java/com/umc/commonplant/domain/user/service/UserService.java
- 회원가입시 이미지 미등록 
- 프로필 이미지 등록 안할시 프론트로 빈문자열 넘겨주도록 수정
- 
- 선택 사항
=> [Refactor] Modify User Join

src/main/java/com/umc/commonplant/domain/plant/controller/PlantController.java, src/main/java/com/umc/commonplant/domain/plant/dto/PlantDto.java, src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java
- 
- Plant 조회/수정 관련 Response 수정
- `PlantDto`의 `getPlant`에 Swagger 설명 추가
=> [Fix] Modify Response classes in PlantDto

src/main/java/com/umc/commonplant/domain/user/service/UserService.java
- 이름 중복검사 리턴값 수정
- 사용가능하면 true 리턴
- 이미 사용중인 이름이면 false 리턴
- 
- 선택 사항
=> [Fix] Fix checkNameDuplication return value

src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java
=> [Chore] place log 추가

src/main/java/com/umc/commonplant/domain/oauth/controller/OAuthController.java, src/main/java/com/umc/commonplant/domain/user/controller/UserController.java
- 유저 도메인 API 로그 작성
- 각 API에 로그 작성
- 
- 선택 사항
=> [Log] Logging User Domain

src/main/java/com/umc/commonplant/domain/plant/dto/PlantDto.java, src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java
- #26 
- 식물 조회를 할 때 식물 관리 팁도 조회되도록 수정
=> [Fix] 식물 조회 API 수정

src/main/java/com/umc/commonplant/domain/plant/controller/PlantSwagger.java, src/main/java/com/umc/commonplant/domain/plant/dto/PlantDto.java, src/main/java/com/umc/commonplant/domain/plant/entity/Plant.java, src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java
- #26
- **🎆 기획 변경**
- 식물 수정할 때 식물의 물 주기 기간 값도 변경 가능하게 하도록 수정
- 물 주기 기간 값 관련 에러 코드 수정
- 식물의 이미지도 변경 가능하게 하도록 수정
=> [Fix] updatePlant 수정

src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java
- #26
- #134 
- 식물 조회할 때 Information에 저장된 값이 아닌, 사용자가 설정한 물 주기 값이 조회되도록 수정
=> [Fix] getPlant 수정

src/main/java/com/umc/commonplant/domain/user/controller/UserController.java, src/main/java/com/umc/commonplant/domain/user/service/UserService.java
- 사용자 프로필 이미지 호출 API
- 글 작성자의 프로필 사진을 가져오는 API 작성
- 
- 선택 사항
=> [Feat] : get User Profile Image Url

build.gradle, src/main/java/com/umc/commonplant/domain/calendar/controller/CalendarController.java, src/main/java/com/umc/commonplant/domain/calendar/dto/CalendarDto.java, src/main/java/com/umc/commonplant/domain/calendar/service/CalendarService.java, src/main/java/com/umc/commonplant/domain/plant/dto/PlantDto.java, src/main/java/com/umc/commonplant/domain/plant/entity/Plant.java, src/main/java/com/umc/commonplant/domain/plant/entity/PlantRepository.java, src/main/java/com/umc/commonplant/domain/plant/service/PlantService.java, src/main/java/com/umc/commonplant/domain/revision/entity/RevisionHistory.java, src/main/java/com/umc/commonplant/global/config/DataEnversConfig.java, src/main/java/com/umc/commonplant/global/exception/ErrorResponseStatus.java
- #74 
- 식물/장소/메모 리스트 불러오는 API 구현
- 식물/장소/메모 리스트 불러오는 API 구현
- 추후 다른 도메인과 연동 예정
- 날짜 별로 불러오는 기능 추가 구현 예정
=> [Feat] Calendar: 월별 조회

src/main/java/com/umc/commonplant/domain/calendar/controller/CalendarController.java
- #141 
- Calendar 도메인에 Log Message 추가
- 일부 주석 수정
=> [Chore] Add Log Message in getCalendarByMonth

src/main/java/com/umc/commonplant/domain/calendar/controller/CalendarController.java, src/main/java/com/umc/commonplant/domain/calendar/controller/CalendarSwagger.java
- #74 
- getCalendarByMonth에 Swagger 적용
- getCalendarByMonth에 Swagger 적용
=> [Feat] Calendar(getCalendarByMonth) Swagger 적용

src/main/java/com/umc/commonplant/domain/calendar/controller/CalendarController.java, src/main/java/com/umc/commonplant/domain/calendar/dto/CalendarDto.java
- #144
- `Operation(hidden=true)' 적용
- [`springdoc`에서 @ApiIgnore를 대체하는 방법](https://github.com/springdoc/springdoc-openapi/issues/109)
=> [Chore] Calendar Swagger 수정

src/main/java/com/umc/commonplant/domain/place/controller/PlaceContoller.java, src/main/java/com/umc/commonplant/domain/place/controller/PlaceSwagger.java, src/main/java/com/umc/commonplant/domain/place/dto/PlaceDto.java, src/main/java/com/umc/commonplant/domain/place/entity/Place.java, src/main/java/com/umc/commonplant/domain/place/service/PlaceService.java
- #18 
- 장소 수정 API 구현
- `PlaceDTO` 설명 수정
=> [Feat] updatePlace
